title: null
description: >
  Empowering tech startups with strategic product-market fit.
  From idea to execution, we help founders craft standout products
  and deliver value across key industries.

seo:
  title: Synthesis Partners | Tech Startup Consultancy

author:
  name: Valentin Podkamennyi
  url: https://vpodk.com
  twitter: vpodk

# theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
