url: https://synthesispartners.co
title: Synthesis Partners - Tech Startup Consultancy
tagline: Turning Startup Ideas Into Market-Winning Products.
description: >-
  Empowering tech startups with strategic product-market fit.
  From idea to execution, we help founders craft standout products
  and deliver value across key industries.

author:
  name: Valentin Podkamennyi
  url: https://vpodk.com
  twitter: vpodk

# theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  enabled: false
  strip_title: false
  collections: false
